language: node_js

env:
 DATABASE_URL || 'postgresql://codex-coder:pg123@localhost:5432/reg'

node_js:  
  - "12"

before_script:
  - psql -c 'create database  reg;' -U postgres
  - psql -U postgres -d reg -a -f reg.sql

services:
  - postgresql